

Version: 'wikidPad 2.4alpha01' Session start: 2018-12-11 06:06:33
Traceback (most recent call last):
  File "D:\Daten\Projekte\Wikidpad\Current_next\lib\pwiki\PersonalWikiFrame.py", line 1969, in <lambda>
  File "D:\Daten\Projekte\Wikidpad\Current_next\lib\pwiki\PersonalWikiFrame.py", line 4727, in showOptionsDialog
  File "D:\Daten\Projekte\Wikidpad\Current_next\lib\pwiki\OptionsDialog.py", line 951, in __init__
AttributeError: 'Panel' object has no attribute 'SetValue'
Traceback (most recent call last):
  File "D:\Daten\Projekte\Wikidpad\Current_next\lib\pwiki\WikiTreeCtrl.py", line 2535, in OnRightButtonUp
AttributeError: 'WikiTreeCtrl' object has no attribute 'PopupMenuXY'
Traceback (most recent call last):
  File "D:\Daten\Projekte\Wikidpad\Current_next\lib\pwiki\WikiTreeCtrl.py", line 2535, in OnRightButtonUp
AttributeError: 'WikiTreeCtrl' object has no attribute 'PopupMenuXY'
Traceback (most recent call last):
  File "D:\Daten\Projekte\Wikidpad\Current_next\lib\pwiki\WikiTreeCtrl.py", line 2535, in OnRightButtonUp
AttributeError: 'WikiTreeCtrl' object has no attribute 'PopupMenuXY'
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 58714)
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python34\lib\socketserver.py", line 305, in _handle_request_noblock
  File "C:\Program Files (x86)\Python34\lib\socketserver.py", line 331, in process_request
  File "C:\Program Files (x86)\Python34\lib\socketserver.py", line 344, in finish_request
  File "C:\Program Files (x86)\Python34\lib\socketserver.py", line 673, in __init__
  File "D:\Daten\Projekte\Wikidpad\Current_next\lib\pwiki\Ipc.py", line 94, in handle
  File "C:\Program Files (x86)\Python34\lib\socket.py", line 398, in write
TypeError: 'str' does not support the buffer interface
----------------------------------------


Version: 'wikidPad 2.4alpha01' Session start: 2018-12-11 10:04:30
Traceback (most recent call last):
  File "D:\Daten\Projekte\Wikidpad\Current_next\lib\pwiki\WikiDocument.py", line 462, in connect
  File "D:\Daten\Projekte\Wikidpad\Current_next\lib\pwiki\WikiDocument.py", line 259, in __call__
  File "D:\Daten\Projekte\Wikidpad\Current_next\lib\pwiki\wikidata\original_sqlite\WikiData.py", line 207, in connect
pwiki.WikiExceptions.DbWriteAccessError: database is locked [5]


Version: 'wikidPad 2.4alpha01' Session start: 2019-04-27 15:13:09
Traceback (most recent call last):
  File "D:\Daten\Projekte\Wikidpad\Current_next\lib\pwiki\Configuration.py", line 245, in loadConfig
FileNotFoundError: [Errno 2] No such file or directory: 'Z:\\home\\rok\\Dropbox\\Public\\ideje_wiki\\Ideje\\Ideje.wiki'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Daten\Projekte\Wikidpad\Current_next\lib\pwiki\WikiDocument.py", line 143, in splitConfigPathAndWord
  File "D:\Daten\Projekte\Wikidpad\Current_next\lib\pwiki\Configuration.py", line 247, in loadConfig
pwiki.WikiExceptions.MissingConfigurationFileException: Config file not found
